### ISSUE TITLE
Can not run migrations

### ISSUE THREAD

**Issue by nemanjam** [nuvic/flask_for_startups#3]
Inside Docker container I installed requirements and when I run `alembic -c migrations/alembic.ini -x db=dev upgrade head` I get this:

```
vscode ➜ /workspace (main) $ alembic -c migrations/alembic.ini -x db=dev upgrade head
Traceback (most recent call last):
  File "/home/vscode/.local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/config.py", line 588, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/config.py", line 582, in main
    self.run_cmd(cfg, options)
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/config.py", line 559, in run_cmd
    fn(
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/command.py", line 320, in upgrade
    script.run_env()
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/vscode/.local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/migrations/env.py", line 16, in <module>
    from app.models import Base
ModuleNotFoundError: No module named 'app'
vscode ➜ /workspace (main) $ 
```

**Comment by nemanjam** [comment]
This fixes it:

```bash
PYTHONPATH=. alembic -c migrations/alembic.ini -x db=dev upgrade head
```
This should fix it in Dockerfile, I haven't rebuilt container yet:

```dockerfile
ENV PYTHONPATH "${PYTHONPATH}:/workspace"
```

**Comment by ser** [comment]
it's not completed as this bug is still in the docs :)
